version: '3.4'

services:
  apiwithpostgredocker:
    container_name: apiwithpostgre_app
    image: ${DOCKER_REGISTRY-}apiwithpostgredocker
    build:
      context: .
      dockerfile: APIWithPostgreDocker/Dockerfile
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=kaushik@123"
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: kaushik@123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

